insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Poem'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Short stories'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Books'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Literature'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Grammar'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Comics'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Music'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Design'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Creativity'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Dance'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Drawing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Art'), (select id from interests where name = 'Animation'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Movies'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Series'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Anime'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Cartoon'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Animation'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Gaming'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Music'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'News'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Cinema'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Exposed'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Entertainment'), (select id from interests where name = 'Unpopular opinion'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Cooking'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Food'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Agriculture'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Festival'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Language'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Philosophy'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Travel'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Clothing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Sacred places'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Environment'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'History'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Astrology'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Ritual'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Freedom'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Lifestyle'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Culture'), (select id from interests where name = 'Pets'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Food'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Fitness'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Self-care'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Skin-care'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Diet'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Yoga'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Mental Health'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Health'), (select id from interests where name = 'Health tips'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Work'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Leadership'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Startup'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Design'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Engineering'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Entrepreneurship'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Venture capitalist'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Product management'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Media'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Business'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Economy'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Photography'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Tourism'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Freelancing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Videography'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Automobile'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Finance'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Industry'), (select id from interests where name = 'Share market'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Creativity'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Learning'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Exploring'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Money'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Writing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Productivity'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Motivation'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Dream'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Growth'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Skill'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Finance'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Stock market'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Self'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Personal development'), (select id from interests where name = 'Education'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Election'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Development'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Social'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Environment'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'History'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Finance'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Politics'), (select id from interests where name = 'Law and order'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'IT'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'Photo editing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'Video editing'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'Hacking'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'Programming'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Software'), (select id from interests where name = 'Technology'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Science'), (select id from interests where name = 'Invention'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Science'), (select id from interests where name = 'Astronomy'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Science'), (select id from interests where name = 'Archeology'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Science'), (select id from interests where name = 'Theories'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Sports'), (select id from interests where name = 'Hockey'));
insert into category_x_interests(category_id, interest_id) values ((select id from interests where name = 'Sports'), (select id from interests where name = 'Cricket'));
