with adminUserID as (select users.id as id
                     from users
                              inner join roles r on r.id = users.role_id
                     where r.name = 'Admin'
                     limit 1)
insert
into interests(id, name, added_by, cover_pic)
values (uuid_generate_v4(), 'Art', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Entertainment', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Culture', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Health', (select id from adminUserID), 'https://pageoneasia.com/controller/images/asia/hjkhjk.jpg'),
       (uuid_generate_v4(), 'Industry', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Personal', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Politics', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Software', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Science', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Sports', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Personal development', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Poem', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Subramanya_Bharathi_1960_stamp_of_India.jpg'),
       (uuid_generate_v4(), 'Short stories', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Books', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Book_fair-Tamil_Nadu-35th-Chennai-january-2012-part_30.JPG'),
       (uuid_generate_v4(), 'Literature', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/6/69/Ancient_Tamil_Script.jpg'),
       (uuid_generate_v4(), 'Grammar', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Comics', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/ta/9/9d/Sirithiran_cartoon_2.JPG'),
       (uuid_generate_v4(), 'Music', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/4/4e/P._Susheela_with_AR_Rahman.jpg'),
       (uuid_generate_v4(), 'Design', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Creativity', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Dance', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Drawing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Animation', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Movies', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Rajinikanth_and_Vijay_at_the_Nadigar_Sangam_Protest.jpg'),
       (uuid_generate_v4(), 'Series', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/1/10/Meta-image-netflix-symbol-black.png'),
       (uuid_generate_v4(), 'Anime', (select id from adminUserID), 'https://www.thenerddaily.com/wp-content/uploads/2018/08/Reasons-To-Watch-Anime.jpg'),
       (uuid_generate_v4(), 'Cartoon', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Gaming', (select id from adminUserID), 'http://www.elitegamerindia.com/img/5a.png'),
       (uuid_generate_v4(), 'News', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Cinema', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Sivaji_Ganesan_1.jpg'),
       (uuid_generate_v4(), 'Exposed', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Unpopular opinion', (select id from adminUserID), 'https://images.unsplash.com/photo-1542490556-9232e06befc7'),
       (uuid_generate_v4(), 'Cooking', (select id from adminUserID), 'https://images.unsplash.com/photo-1604740795024-c06eeca4bf89'),
       (uuid_generate_v4(), 'Food', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Agriculture', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/f/f1/%281%29_Agriculture_and_rural_farms_of_India.jpg'),
       (uuid_generate_v4(), 'Festival', (select id from adminUserID), 'https://images.unsplash.com/photo-1576394435759-02a2674ff6e0'),
       (uuid_generate_v4(), 'Language', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/3/35/Word_Tamil.svg'),
       (uuid_generate_v4(), 'Philosophy', (select id from adminUserID), 'https://en.wikipedia.org/wiki/Swami_Vivekananda#/media/File:Swami_Vivekananda-1893-09-signed.jpg'),
       (uuid_generate_v4(), 'Travel', (select id from adminUserID), 'https://images.unsplash.com/photo-1595503867626-fc2d52c0218a'),
       (uuid_generate_v4(), 'Clothing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Sacred places', (select id from adminUserID), 'https://images.unsplash.com/photo-1572146462570-2129a547e6dd'),
       (uuid_generate_v4(), 'Environment', (select id from adminUserID), 'https://images.unsplash.com/photo-1576054132013-d848d0fa7d93'),
       (uuid_generate_v4(), 'History', (select id from adminUserID), 'https://images.unsplash.com/photo-1607016383084-8f8d1358161c'),
       (uuid_generate_v4(), 'Astrology', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Zodiac_symbols_painted_Relief_on_the_terrace_of_a_Gopuram_at_Kanipakam.jpg'),
       (uuid_generate_v4(), 'Ritual', (select id from adminUserID), 'https://images.unsplash.com/photo-1585563741139-4d488b8291c4'),
       (uuid_generate_v4(), 'Freedom', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Lifestyle', (select id from adminUserID), 'https://images.unsplash.com/photo-1524080989185-22b076ffb631'),
       (uuid_generate_v4(), 'Pets', (select id from adminUserID), 'https://images.unsplash.com/photo-1546722228-7baeca4bd0b3'),
       (uuid_generate_v4(), 'Fitness', (select id from adminUserID), 'https://images.unsplash.com/photo-1506126613408-eca07ce68773'),
       (uuid_generate_v4(), 'Self-care', (select id from adminUserID), 'https://images.unsplash.com/photo-1505932794465-147d1f1b2c97'),
       (uuid_generate_v4(), 'Skin-care', (select id from adminUserID), 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273'),
       (uuid_generate_v4(), 'Diet', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Yoga', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Mental Health', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Health tips', (select id from adminUserID), 'https://images.unsplash.com/photo-1498837167922-ddd27525d352'),
       (uuid_generate_v4(), 'Work', (select id from adminUserID), 'https://images.unsplash.com/photo-1532448416606-00984ce2cde9'),
       (uuid_generate_v4(), 'Leadership', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Startup', (select id from adminUserID), 'https://images.unsplash.com/photo-1511729530272-7198cdce7b8a'),
       (uuid_generate_v4(), 'Engineering', (select id from adminUserID), 'https://images.unsplash.com/photo-1581093806997-124204d9fa9d'),
       (uuid_generate_v4(), 'Entrepreneurship', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Venture capitalist', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Product management', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Media', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Business', (select id from adminUserID), 'https://images.unsplash.com/photo-1508385082359-f38ae991e8f2'),
       (uuid_generate_v4(), 'Economy', (select id from adminUserID), 'https://images.unsplash.com/photo-1509603148757-f2a393f18afa'),
       (uuid_generate_v4(), 'Photography', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Tourism', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Freelancing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Videography', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Automobile', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/a/a8/CarService.JPG'),
       (uuid_generate_v4(), 'Finance', (select id from adminUserID), 'https://images.unsplash.com/photo-1565514159479-989ff4504071'),
       (uuid_generate_v4(), 'Share market', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Nifty_weekly_chart_with_200MA_by_me.png'),
       (uuid_generate_v4(), 'Learning', (select id from adminUserID), 'https://images.unsplash.com/photo-1600195077909-46e573870d99'),
       (uuid_generate_v4(), 'Exploring', (select id from adminUserID), 'https://images.unsplash.com/photo-1512441126141-b4382f37f112'),
       (uuid_generate_v4(), 'Money', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Writing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Productivity', (select id from adminUserID), 'https://images.unsplash.com/photo-1502945015378-0e284ca1a5be'),
       (uuid_generate_v4(), 'Motivation', (select id from adminUserID), 'https://images.unsplash.com/photo-1531323386183-43890b5c766d'),
       (uuid_generate_v4(), 'Dream', (select id from adminUserID), 'https://images.unsplash.com/photo-1495539406979-bf61750d38ad'),
       (uuid_generate_v4(), 'Growth', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Skill', (select id from adminUserID), 'https://images.unsplash.com/photo-1593766818891-892421791902'),
       (uuid_generate_v4(), 'Stock market', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Self', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Education', (select id from adminUserID), 'https://images.unsplash.com/photo-1524069290683-0457abfe42c3'),
       (uuid_generate_v4(), 'Election', (select id from adminUserID), 'https://en.wikipedia.org/wiki/Politics_of_Tamil_Nadu#/media/File:TamilNadu_Logo.svg'),
       (uuid_generate_v4(), 'Development', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Social', (select id from adminUserID), 'https://images.unsplash.com/photo-1526572690437-c3f99d109cfd'),
       (uuid_generate_v4(), 'Law and order', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/6/62/Chennai_High_Court.jpg'),
       (uuid_generate_v4(), 'IT', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/5/52/India_Land_Tech_Park%2CAmbattur.JPG'),
       (uuid_generate_v4(), 'Photo editing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Video editing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Hacking', (select id from adminUserID), 'https://images.unsplash.com/photo-1544890225-2f3faec4cd60'),
       (uuid_generate_v4(), 'Programming', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/5/50/Wikipedia_Academy_Preparation_-_Visveswaraya_Guest_House_-_Indian_Institute_of_Technology_-_Kharagpur_-_West_Midnapore_2015-01-24_4939.JPG'),
       (uuid_generate_v4(), 'Technology', (select id from adminUserID), 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e'),
       (uuid_generate_v4(), 'Invention', (select id from adminUserID), 'https://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam#/media/File:A._P._J._Abdul_Kalam.jpg'),
       (uuid_generate_v4(), 'Astronomy', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Kalpana_Chawla%2C_NASA_photo_portrait_in_orange_suit.jpg/330px-Kalpana_Chawla%2C_NASA_photo_portrait_in_orange_suit.jpg'),
       (uuid_generate_v4(), 'Archeology', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/5/57/KeeladiExcavationCamp2.jpg'),
       (uuid_generate_v4(), 'Theories', (select id from adminUserID), 'https://images.unsplash.com/photo-1447600514716-ca6f3974c346'),
       (uuid_generate_v4(), 'Hockey', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Cricket', (select id from adminUserID), 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/IPL_T20_Chennai_vs_Kolkata.JPG/1200px-IPL_T20_Chennai_vs_Kolkata.JPG'),
       (uuid_generate_v4(), 'Kabadi', (select id from adminUserID), 'https://en.wikipedia.org/wiki/Sports_in_Tamil_Nadu#/media/File:Sadugudu_sadugude.jpg'),
       (uuid_generate_v4(), 'Cock fight', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Jallikattu', (select id from adminUserID), 'https://en.wikipedia.org/wiki/Sports_in_Tamil_Nadu#/media/File:A_bull_being_tamed_in_Jallikattu_held_in_palamedu.jpg');
