with adminUserID as (select admin.id as id
                     from admin
                              inner join roles r on r.id = admin.role_id
                     where r.name = 'Admin'
                     limit 1)
insert
into interests(id, name, approved_by, cover_pic)
values (uuid_generate_v4(), 'Art', (select id from adminUserID), 'interest/art.jpg'),
       (uuid_generate_v4(), 'Entertainment', (select id from adminUserID), 'interest/entertainment.jpg'),
       (uuid_generate_v4(), 'Culture', (select id from adminUserID), 'interest/culture.jpg'),
       (uuid_generate_v4(), 'Health', (select id from adminUserID), 'interest/health.jpg'),
       (uuid_generate_v4(), 'Industry', (select id from adminUserID), 'interest/industry.jpg'),
       (uuid_generate_v4(), 'Personal', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Politics', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Software', (select id from adminUserID), 'interest/software.png'),
       (uuid_generate_v4(), 'Science', (select id from adminUserID), 'interest/science.jpg'),
       (uuid_generate_v4(), 'Sports', (select id from adminUserID), 'interest/sports.jpg'),
       (uuid_generate_v4(), 'Personal development', (select id from adminUserID), 'interest/personal_development.svg'),
       (uuid_generate_v4(), 'Poem', (select id from adminUserID), 'interest/poem.jpg'),
       (uuid_generate_v4(), 'Short stories', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Books', (select id from adminUserID), 'interest/books.JPG'),
       (uuid_generate_v4(), 'Literature', (select id from adminUserID), 'interest/literature.jpg'),
       (uuid_generate_v4(), 'Grammar', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Comics', (select id from adminUserID), 'interest/comics.JPG'),
       (uuid_generate_v4(), 'Music', (select id from adminUserID), 'interest/music.jpg'),
       (uuid_generate_v4(), 'Design', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Creativity', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Dance', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Drawing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Animation', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Movies', (select id from adminUserID), 'interest/movies.jpg'),
       (uuid_generate_v4(), 'Series', (select id from adminUserID), 'interest/series.png'),
       (uuid_generate_v4(), 'Anime', (select id from adminUserID), 'interest/anime.jpg'),
       (uuid_generate_v4(), 'Cartoon', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Gaming', (select id from adminUserID), 'interest/gaming.png'),
       (uuid_generate_v4(), 'News', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Cinema', (select id from adminUserID), 'interest/cinema.jpg'),
       (uuid_generate_v4(), 'Exposed', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Unpopular opinion', (select id from adminUserID), 'interest/unpopular_opinion.avif'),
       (uuid_generate_v4(), 'Cooking', (select id from adminUserID), 'interest/cooking.avif'),
       (uuid_generate_v4(), 'Food', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Agriculture', (select id from adminUserID), 'interest/agriculture.jpg'),
       (uuid_generate_v4(), 'Festival', (select id from adminUserID), 'interest/festival.avif'),
       (uuid_generate_v4(), 'Language', (select id from adminUserID), 'interest/language.svg'),
       (uuid_generate_v4(), 'Philosophy', (select id from adminUserID), 'interest/philosophy.jpg'),
       (uuid_generate_v4(), 'Travel', (select id from adminUserID), 'interest/travel.avif'),
       (uuid_generate_v4(), 'Clothing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Sacred places', (select id from adminUserID), 'interest/sacred places.avif'),
       (uuid_generate_v4(), 'Environment', (select id from adminUserID), 'interest/environment.avif'),
       (uuid_generate_v4(), 'History', (select id from adminUserID), 'interest/history.avif'),
       (uuid_generate_v4(), 'Astrology', (select id from adminUserID), 'interest/astrology.jpg'),
       (uuid_generate_v4(), 'Ritual', (select id from adminUserID), 'interest/ritual.avif'),
       (uuid_generate_v4(), 'Freedom', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Lifestyle', (select id from adminUserID), 'interest/lifestyle.avif'),
       (uuid_generate_v4(), 'Pets', (select id from adminUserID), 'interest/pets.avif'),
       (uuid_generate_v4(), 'Fitness', (select id from adminUserID), 'interest/fitness.avif'),
       (uuid_generate_v4(), 'Self-care', (select id from adminUserID), 'interest/self-care.jpeg'),
       (uuid_generate_v4(), 'Skin-care', (select id from adminUserID), 'interest/skin_care.avif'),
       (uuid_generate_v4(), 'Diet', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Yoga', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Mental Health', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Health tips', (select id from adminUserID), 'interest/health_tips.avif'),
       (uuid_generate_v4(), 'Work', (select id from adminUserID), 'interest/work.avif'),
       (uuid_generate_v4(), 'Leadership', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Startup', (select id from adminUserID), 'interest/start_up.avif'),
       (uuid_generate_v4(), 'Engineering', (select id from adminUserID), 'interest/engineering.avif'),
       (uuid_generate_v4(), 'Entrepreneurship', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Venture capitalist', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Product management', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Media', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Business', (select id from adminUserID), 'interest/business.avif'),
       (uuid_generate_v4(), 'Economy', (select id from adminUserID), 'interest/economy.avif'),
       (uuid_generate_v4(), 'Photography', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Tourism', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Freelancing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Videography', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Automobile', (select id from adminUserID), 'interest/automobile.JPG'),
       (uuid_generate_v4(), 'Finance', (select id from adminUserID), 'interest/finance.avif'),
       (uuid_generate_v4(), 'Share market', (select id from adminUserID), 'interest/share_market.png'),
       (uuid_generate_v4(), 'Learning', (select id from adminUserID), 'interest/learning.avif'),
       (uuid_generate_v4(), 'Exploring', (select id from adminUserID), 'interest/exploring.avif'),
       (uuid_generate_v4(), 'Money', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Writing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Productivity', (select id from adminUserID), 'interest/productivity.avif'),
       (uuid_generate_v4(), 'Motivation', (select id from adminUserID), 'interest/motivation.avif'),
       (uuid_generate_v4(), 'Dream', (select id from adminUserID), 'interest/dream.avif'),
       (uuid_generate_v4(), 'Growth', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Skill', (select id from adminUserID), 'interest/skill.avif'),
       (uuid_generate_v4(), 'Stock market', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Self', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Education', (select id from adminUserID), 'interest/education.avif'),
       (uuid_generate_v4(), 'Election', (select id from adminUserID), 'interest/election.png'),
       (uuid_generate_v4(), 'Development', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Social', (select id from adminUserID), 'interest/social.avif'),
       (uuid_generate_v4(), 'Law and order', (select id from adminUserID), 'interest/law_and_order.jpg'),
       (uuid_generate_v4(), 'IT', (select id from adminUserID), 'interest/it.JPG'),
       (uuid_generate_v4(), 'Photo editing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Video editing', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Hacking', (select id from adminUserID), 'interest/hacking.avif'),
       (uuid_generate_v4(), 'Programming', (select id from adminUserID), 'interest/programming.JPG'),
       (uuid_generate_v4(), 'Technology', (select id from adminUserID), 'interest/technology.avif'),
       (uuid_generate_v4(), 'Invention', (select id from adminUserID), 'interest/invention.jpg'),
       (uuid_generate_v4(), 'Astronomy', (select id from adminUserID), 'interest/astronomy.jpg'),
       (uuid_generate_v4(), 'Archeology', (select id from adminUserID), 'interest/archeology.jpg'),
       (uuid_generate_v4(), 'Theories', (select id from adminUserID), 'interest/theories.avif'),
       (uuid_generate_v4(), 'Hockey', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Cricket', (select id from adminUserID), 'interest/cricket.JPG'),
       (uuid_generate_v4(), 'Kabadi', (select id from adminUserID), 'interest/kabadi.jpg'),
       (uuid_generate_v4(), 'Cock fight', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Jallikattu', (select id from adminUserID), 'interest/jallikatu.jpg');
