with adminUserID as (select admin.id as id
                     from admin
                              inner join roles r on r.id = admin.role_id
                     where r.name = 'Admin'
                     limit 1)
insert
into interests(id, name, approved_by, cover_pic)
values (uuid_generate_v4(), 'Art', (select id from adminUserID), 'interest/art.jpeg'),
       (uuid_generate_v4(), 'Entertainment', (select id from adminUserID), 'interest/entertainment.jpeg'),
       (uuid_generate_v4(), 'Culture', (select id from adminUserID), 'interest/culture.jpeg'),
       (uuid_generate_v4(), 'Health', (select id from adminUserID), 'interest/health.jpeg'),
       (uuid_generate_v4(), 'Industry', (select id from adminUserID), 'interest/industry.jpeg'),
       (uuid_generate_v4(), 'Personal', (select id from adminUserID), 'interest/personal.jpeg'),
       (uuid_generate_v4(), 'Politics', (select id from adminUserID), 'interest/politics.jpeg'),
       (uuid_generate_v4(), 'Software', (select id from adminUserID), 'interest/software.jpeg'),
       (uuid_generate_v4(), 'Science', (select id from adminUserID), 'interest/science.jpeg'),
       (uuid_generate_v4(), 'Sports', (select id from adminUserID), 'interest/sports.jpeg'),
       (uuid_generate_v4(), 'Personal development', (select id from adminUserID), 'interest/personal_development.jpeg'),
       (uuid_generate_v4(), 'Poem', (select id from adminUserID), 'interest/poem.jpeg'),
       (uuid_generate_v4(), 'Short stories', (select id from adminUserID), 'interest/short_stories.jpeg'),
       (uuid_generate_v4(), 'Books', (select id from adminUserID), 'interest/books.jpeg'),
       (uuid_generate_v4(), 'Literature', (select id from adminUserID), 'interest/literature.jpeg'),
       (uuid_generate_v4(), 'Grammar', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Comics', (select id from adminUserID), 'interest/comics.jpeg'),
       (uuid_generate_v4(), 'Music', (select id from adminUserID), 'interest/music.jpeg'),
       (uuid_generate_v4(), 'Design', (select id from adminUserID), 'interest/design.jpeg'),
       (uuid_generate_v4(), 'Creativity', (select id from adminUserID), 'interest/creativity.jpeg'),
       (uuid_generate_v4(), 'Dance', (select id from adminUserID), 'interest/dance.jpeg'),
       (uuid_generate_v4(), 'Drawing', (select id from adminUserID), 'interest/drawing.jpeg'),
       (uuid_generate_v4(), 'Animation', (select id from adminUserID), 'interest/animation.jpeg'),
       (uuid_generate_v4(), 'Movies', (select id from adminUserID), 'interest/movies.jpeg'),
       (uuid_generate_v4(), 'Series', (select id from adminUserID), 'interest/series.jpeg'),
       (uuid_generate_v4(), 'Anime', (select id from adminUserID), 'interest/anime.jpeg'),
       (uuid_generate_v4(), 'Cartoon', (select id from adminUserID), 'interest/cartoon.jpeg'),
       (uuid_generate_v4(), 'Gaming', (select id from adminUserID), 'interest/gaming.jpeg'),
       (uuid_generate_v4(), 'News', (select id from adminUserID), 'interest/news.jpeg'),
       (uuid_generate_v4(), 'Cinema', (select id from adminUserID), 'interest/cinema.jpg'),
       (uuid_generate_v4(), 'Exposed', (select id from adminUserID), 'interest/exposed.jpeg'),
       (uuid_generate_v4(), 'Unpopular opinion', (select id from adminUserID), 'interest/unpopular_opinion.jpeg'),
       (uuid_generate_v4(), 'Cooking', (select id from adminUserID), 'interest/cooking.jpeg'),
       (uuid_generate_v4(), 'Food', (select id from adminUserID), 'interest/food.jpeg'),
       (uuid_generate_v4(), 'Agriculture', (select id from adminUserID), 'interest/agriculture.jpeg'),
       (uuid_generate_v4(), 'Festival', (select id from adminUserID), 'interest/festival.jpeg'),
       (uuid_generate_v4(), 'Language', (select id from adminUserID), 'interest/language.jpeg'),
       (uuid_generate_v4(), 'Philosophy', (select id from adminUserID), 'interest/philosophy.jpeg'),
       (uuid_generate_v4(), 'Travel', (select id from adminUserID), 'interest/travel.jpeg'),
       (uuid_generate_v4(), 'Clothing', (select id from adminUserID), 'interest/clothing.jpeg'),
       (uuid_generate_v4(), 'Sacred places', (select id from adminUserID), 'interest/sacred places.jpeg'),
       (uuid_generate_v4(), 'Environment', (select id from adminUserID), 'interest/environment.jpeg'),
       (uuid_generate_v4(), 'History', (select id from adminUserID), 'interest/history.jpeg'),
       (uuid_generate_v4(), 'Astrology', (select id from adminUserID), 'interest/astrology.jpeg'),
       (uuid_generate_v4(), 'Ritual', (select id from adminUserID), 'interest/ritual.jpeg'),
       (uuid_generate_v4(), 'Freedom', (select id from adminUserID), 'interest/freedom.jpeg'),
       (uuid_generate_v4(), 'Lifestyle', (select id from adminUserID), 'interest/lifestyle.jpeg'),
       (uuid_generate_v4(), 'Pets', (select id from adminUserID), 'interest/pets.jpeg'),
       (uuid_generate_v4(), 'Fitness', (select id from adminUserID), 'interest/fitness.jpeg'),
       (uuid_generate_v4(), 'Self-care', (select id from adminUserID), 'interest/self-care.jpeg'),
       (uuid_generate_v4(), 'Skin-care', (select id from adminUserID), 'interest/skin_care.jpeg'),
       (uuid_generate_v4(), 'Diet', (select id from adminUserID), 'interest/diet.jpeg'),
       (uuid_generate_v4(), 'Yoga', (select id from adminUserID), 'interest/yoga.jpeg'),
       (uuid_generate_v4(), 'Mental Health', (select id from adminUserID), 'interest/mental_health.jpeg'),
       (uuid_generate_v4(), 'Health tips', (select id from adminUserID), 'interest/health_tips.jpeg'),
       (uuid_generate_v4(), 'Work', (select id from adminUserID), 'interest/work.jpeg'),
       (uuid_generate_v4(), 'Leadership', (select id from adminUserID), 'interest/leadership.jpeg'),
       (uuid_generate_v4(), 'Startup', (select id from adminUserID), 'interest/startup.jpeg'),
       (uuid_generate_v4(), 'Engineering', (select id from adminUserID), 'interest/engineering.jpeg'),
       (uuid_generate_v4(), 'Entrepreneurship', (select id from adminUserID), 'interest/entrepreneurship.jpeg'),
       (uuid_generate_v4(), 'Venture capitalist', (select id from adminUserID), 'interest/venture_capitalist.png'),
       (uuid_generate_v4(), 'Product management', (select id from adminUserID), 'interest/product_management.jpeg'),
       (uuid_generate_v4(), 'Media', (select id from adminUserID), 'interest/media.jpeg'),
       (uuid_generate_v4(), 'Business', (select id from adminUserID), 'interest/business.jpeg'),
       (uuid_generate_v4(), 'Economy', (select id from adminUserID), 'interest/economy.jpeg'),
       (uuid_generate_v4(), 'Photography', (select id from adminUserID), 'interest/photography.jpeg'),
       (uuid_generate_v4(), 'Tourism', (select id from adminUserID), null),
       (uuid_generate_v4(), 'Freelancing', (select id from adminUserID), 'interest/freelancing.jpeg'),
       (uuid_generate_v4(), 'Videography', (select id from adminUserID), 'interest/videography.jpeg'),
       (uuid_generate_v4(), 'Automobile', (select id from adminUserID), 'interest/automobile.jpeg'),
       (uuid_generate_v4(), 'Finance', (select id from adminUserID), 'interest/finance.jpeg'),
       (uuid_generate_v4(), 'Share market', (select id from adminUserID), 'interest/share_market.jpeg'),
       (uuid_generate_v4(), 'Learning', (select id from adminUserID), 'interest/learning.jpeg'),
       (uuid_generate_v4(), 'Exploring', (select id from adminUserID), 'interest/exploring.jpeg'),
       (uuid_generate_v4(), 'Money', (select id from adminUserID), 'interest/money.jpeg'),
       (uuid_generate_v4(), 'Writing', (select id from adminUserID), 'interest/writing.jpeg'),
       (uuid_generate_v4(), 'Productivity', (select id from adminUserID), 'interest/productivity.jpeg'),
       (uuid_generate_v4(), 'Motivation', (select id from adminUserID), 'interest/motivation.jpeg'),
       (uuid_generate_v4(), 'Dream', (select id from adminUserID), 'interest/dream.jpeg'),
       (uuid_generate_v4(), 'Growth', (select id from adminUserID), 'interest/growth.jpeg'),
       (uuid_generate_v4(), 'Skill', (select id from adminUserID), 'interest/skill.jpeg'),
       (uuid_generate_v4(), 'Stock market', (select id from adminUserID), 'interest/stock_market.jpeg'),
       (uuid_generate_v4(), 'Self', (select id from adminUserID), 'interest/self.jpeg'),
       (uuid_generate_v4(), 'Education', (select id from adminUserID), 'interest/education.jpeg'),
       (uuid_generate_v4(), 'Election', (select id from adminUserID), 'interest/election.jpeg'),
       (uuid_generate_v4(), 'Development', (select id from adminUserID), 'interest/development.png'),
       (uuid_generate_v4(), 'Social', (select id from adminUserID), 'interest/social.jpeg'),
       (uuid_generate_v4(), 'Law and order', (select id from adminUserID), 'interest/law_and_order.jpeg'),
       (uuid_generate_v4(), 'IT', (select id from adminUserID), 'interest/it.jpeg'),
       (uuid_generate_v4(), 'Photo editing', (select id from adminUserID), 'interest/photo_editing.jpeg'),
       (uuid_generate_v4(), 'Video editing', (select id from adminUserID), 'interest/video_editing.jpeg'),
       (uuid_generate_v4(), 'Hacking', (select id from adminUserID), 'interest/hacking.jpeg'),
       (uuid_generate_v4(), 'Programming', (select id from adminUserID), 'interest/programming.jpeg'),
       (uuid_generate_v4(), 'Technology', (select id from adminUserID), 'interest/technology.jpeg'),
       (uuid_generate_v4(), 'Invention', (select id from adminUserID), 'interest/invention.jpeg'),
       (uuid_generate_v4(), 'Astronomy', (select id from adminUserID), 'interest/astronomy.jpeg'),
       (uuid_generate_v4(), 'Archeology', (select id from adminUserID), 'interest/archeology.jpeg'),
       (uuid_generate_v4(), 'Theories', (select id from adminUserID), 'interest/theories.jpeg'),
       (uuid_generate_v4(), 'Hockey', (select id from adminUserID), 'interest/hockey.avif'),
       (uuid_generate_v4(), 'Cricket', (select id from adminUserID), 'interest/cricket.webp');