// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	golaerror "github.com/gola-glitch/gola-utils/golaerror"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchUserFollowingInterests mocks base method
func (m *MockClient) FetchUserFollowingInterests(ctx context.Context) ([]string, *golaerror.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUserFollowingInterests", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*golaerror.Error)
	return ret0, ret1
}

// FetchUserFollowingInterests indicates an expected call of FetchUserFollowingInterests
func (mr *MockClientMockRecorder) FetchUserFollowingInterests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUserFollowingInterests", reflect.TypeOf((*MockClient)(nil).FetchUserFollowingInterests), ctx)
}
