DROP SCHEMA IF EXISTS POST_TEST;
CREATE DATABASE POST_TEST;
DROP USER IF EXISTS POST_TEST;
CREATE USER 'POST_TEST'@'%' IDENTIFIED BY 'gola';
GRANT ALL PRIVILEGES ON POST_TEST.* TO 'POST_TEST'@'%';
FLUSH PRIVILEGES;
