DROP USER IF EXISTS POST_TEST;
CREATE USER 'POST_TEST'@'%' IDENTIFIED BY 'gola';
GRANT ALL PRIVILEGES ON * . * TO 'POST_TEST'@'%';
FLUSH PRIVILEGES;
DROP SCHEMA IF EXISTS POST_TEST;
CREATE DATABASE POST_TEST;
