DROP USER IF EXISTS POST;
CREATE USER POST WITH PASSWORD 'gola';
DROP DATABASE IF EXISTS POST;
CREATE DATABASE POST WITH OWNER POST;
GRANT ALL PRIVILEGES ON DATABASE POST TO POST;

DROP USER IF EXISTS hydra;
CREATE USER hydra WITH PASSWORD 'secret';
DROP DATABASE IF EXISTS hydra;
CREATE DATABASE hydra WITH OWNER hydra;
GRANT ALL PRIVILEGES ON DATABASE hydra TO hydra;
