DROP USER IF EXISTS POST_TEST;
CREATE USER POST_TEST WITH PASSWORD 'gola';
DROP DATABASE IF EXISTS POST_TEST;
CREATE DATABASE POST_TEST WITH OWNER POST_TEST;
GRANT ALL PRIVILEGES ON DATABASE POST_TEST TO POST_TEST;
