DROP USER IF EXISTS POST;
CREATE USER POST WITH PASSWORD 'gola';
DROP DATABASE IF EXISTS POST;
DROP ROLE IF EXISTS story;
CREATE ROLE story;
GRANT story TO "SYS";
CREATE DATABASE POST OWNER = story;
GRANT ALL PRIVILEGES ON DATABASE POST TO POST;
