name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#   build-and-publish:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
      
#     - name: Install dependencies
#       run: make install_deps
#       env:
#           ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
#           ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
#     - name: Run build
#       run: make build
#       env:
#           ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
#           ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
#     - name: Run dockerize
#       run: make dockerize
#       env:
#           ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
#           ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

#     - name: Run publish
#       run: make publish
#       env:
#           ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
#           ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

  dev_deploy:
#     needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to dev
      run: make deploy_dev
      env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ACTION: ${{ secrets.ACTION }}
          INVENTORY: ${{ secrets.INVENTORY }}
          PROJECT: ${{ secrets.PROJECT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
